version: '3.4'

services:

  ddagent:
    image: datadog/agent:latest
    environment:
      - DD_APM_ENABLED=true
      - DD_API_KEY=[DATADOG_API_KEY]
      - DD_PROCESS_AGENT_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_SYSTEM_PROBE_ENABLED=true
      - DD_APM_ENV=microsoft
      - DD_TRACE_ANALYTICS_ENABLED=true
      - DD_DOCKER_LABELS_AS_TAGS={"com.docker.compose.service":"service"}
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
     - /sys/kernel/debug:/sys/kernel/debug
    cap_add:
     - SYS_ADMIN
     - SYS_RESOURCE
     - SYS_PTRACE
     - NET_ADMIN
    ports:
      - "8126:8126/tcp"

  seq:
    image: datalust/seq:latest

  sql.data:
    image: mcr.microsoft.com/mssql/server:2017-latest

  nosql.data:
    image: mongo

  basket.data:
    image: redis:alpine

  rabbitmq:
    image: rabbitmq:3-management-alpine

  identity.api:
    image: ${REGISTRY:-eshop}/identity.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.API/Dockerfile
    environment:
      - DD_TRACE_AGENT_HOSTNAME=ddagent
      - DD_TRACE_AGENT_PORT=8126
      - DD_LOGS_INJECTION=true
      - DD_HttpMessageHandler_ENABLED=false
      - DD_TRACE_ANALYTICS_ENABLED=true
      - DD_ADONET_ANALYTICS_ENABLED=true
      - DD_ASPNETMVC_ANALYTICS_ENABLED=true
      - DD_WebRequest_ANALYTICS_ENABLED=true
      - DD_SYSTEM_PROBE_ENABLED=true
    depends_on:
      - sql.data
      - ddagent

  basket.api:
    image: ${REGISTRY:-eshop}/basket.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Basket/Basket.API/Dockerfile
    environment:
      - DD_TRACE_AGENT_HOSTNAME=ddagent
      - DD_TRACE_AGENT_PORT=8126
      - DD_LOGS_INJECTION=true
      - DD_HttpMessageHandler_ENABLED=false
      - DD_TRACE_ANALYTICS_ENABLED=true
      - DD_ADONET_ANALYTICS_ENABLED=true
      - DD_ASPNETMVC_ANALYTICS_ENABLED=true
      - DD_WebRequest_ANALYTICS_ENABLED=true
      - DD_SYSTEM_PROBE_ENABLED=true
    depends_on:
      - basket.data
      - identity.api
      - rabbitmq
      - ddagent

  catalog.api:
    image: ${REGISTRY:-eshop}/catalog.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile
    environment:
      - DD_TRACE_AGENT_HOSTNAME=ddagent
      - DD_TRACE_AGENT_PORT=8126
      - DD_LOGS_INJECTION=true
      - DD_HttpMessageHandler_ENABLED=false
      - DD_TRACE_ANALYTICS_ENABLED=true
      - DD_ADONET_ANALYTICS_ENABLED=true
      - DD_ASPNETMVC_ANALYTICS_ENABLED=true
      - DD_WebRequest_ANALYTICS_ENABLED=true
      - DD_SYSTEM_PROBE_ENABLED=true
    depends_on:
      - sql.data
      - rabbitmq
      - ddagent

  ordering.api:
    image: ${REGISTRY:-eshop}/ordering.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Ordering/Ordering.API/Dockerfile
    environment:
      - DD_TRACE_AGENT_HOSTNAME=ddagent
      - DD_TRACE_AGENT_PORT=8126
      - DD_LOGS_INJECTION=true
      - DD_HttpMessageHandler_ENABLED=false
      - DD_TRACE_ANALYTICS_ENABLED=true
      - DD_ADONET_ANALYTICS_ENABLED=true
      - DD_ASPNETMVC_ANALYTICS_ENABLED=true
      - DD_WebRequest_ANALYTICS_ENABLED=true
      - DD_SYSTEM_PROBE_ENABLED=true
    depends_on:
      - sql.data
      - rabbitmq
      - ddagent

  ordering.backgroundtasks:
    image: ${REGISTRY:-eshop}/ordering.backgroundtasks:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Ordering/Ordering.BackgroundTasks/Dockerfile
    environment:
      - DD_TRACE_AGENT_HOSTNAME=ddagent
      - DD_TRACE_AGENT_PORT=8126
      - DD_LOGS_INJECTION=true
      - DD_HttpMessageHandler_ENABLED=false
      - DD_TRACE_ANALYTICS_ENABLED=true
      - DD_ADONET_ANALYTICS_ENABLED=true
      - DD_ASPNETMVC_ANALYTICS_ENABLED=true
      - DD_WebRequest_ANALYTICS_ENABLED=true
      - DD_SYSTEM_PROBE_ENABLED=true
    depends_on:
      - sql.data
      - rabbitmq
      - ddagent

  marketing.api:
    image: ${REGISTRY:-eshop}/marketing.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Marketing/Marketing.API/Dockerfile
    environment:
      - DD_TRACE_AGENT_HOSTNAME=ddagent
      - DD_TRACE_AGENT_PORT=8126
      - DD_LOGS_INJECTION=true
      - DD_HttpMessageHandler_ENABLED=false
      - DD_TRACE_ANALYTICS_ENABLED=true
      - DD_ADONET_ANALYTICS_ENABLED=true
      - DD_ASPNETMVC_ANALYTICS_ENABLED=true
      - DD_WebRequest_ANALYTICS_ENABLED=true
      - DD_SYSTEM_PROBE_ENABLED=true
    depends_on:
      - sql.data
      - nosql.data
      - identity.api
      - rabbitmq
      - ddagent

  payment.api:
    image: ${REGISTRY:-eshop}/payment.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Payment/Payment.API/Dockerfile
    environment:
      - DD_TRACE_AGENT_HOSTNAME=ddagent
      - DD_TRACE_AGENT_PORT=8126
      - DD_LOGS_INJECTION=true
      - DD_HttpMessageHandler_ENABLED=false
      - DD_TRACE_ANALYTICS_ENABLED=true
      - DD_ADONET_ANALYTICS_ENABLED=true
      - DD_ASPNETMVC_ANALYTICS_ENABLED=true
      - DD_WebRequest_ANALYTICS_ENABLED=true
      - DD_SYSTEM_PROBE_ENABLED=true
    depends_on:
      - rabbitmq
      - ddagent

  locations.api:
    image: ${REGISTRY:-eshop}/locations.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Location/Locations.API/Dockerfile
    environment:
      - DD_TRACE_AGENT_HOSTNAME=ddagent
      - DD_TRACE_AGENT_PORT=8126
      - DD_LOGS_INJECTION=true
      - DD_HttpMessageHandler_ENABLED=false
      - DD_TRACE_ANALYTICS_ENABLED=true
      - DD_ADONET_ANALYTICS_ENABLED=true
      - DD_ASPNETMVC_ANALYTICS_ENABLED=true
      - DD_WebRequest_ANALYTICS_ENABLED=true
      - DD_SYSTEM_PROBE_ENABLED=true
    depends_on:
      - nosql.data
      - rabbitmq
      - ddagent

  webhooks.api:
    image: ${REGISTRY:-eshop}/webhooks.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Webhooks/Webhooks.API/Dockerfile
    environment:
      - DD_TRACE_AGENT_HOSTNAME=ddagent
      - DD_TRACE_AGENT_PORT=8126
      - DD_LOGS_INJECTION=true
      - DD_HttpMessageHandler_ENABLED=false
      - DD_TRACE_ANALYTICS_ENABLED=true
      - DD_ADONET_ANALYTICS_ENABLED=true
      - DD_ASPNETMVC_ANALYTICS_ENABLED=true
      - DD_WebRequest_ANALYTICS_ENABLED=true
      - DD_SYSTEM_PROBE_ENABLED=true
    depends_on:
      - sql.data
      - ddagent

  mobileshoppingapigw:
    image: ${REGISTRY:-eshop}/ocelotapigw:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGw-Base/Dockerfile
    environment:
      - DD_TRACE_AGENT_HOSTNAME=ddagent
      - DD_TRACE_AGENT_PORT=8126
      - DD_LOGS_INJECTION=true
      - DD_HttpMessageHandler_ENABLED=false
      - DD_TRACE_ANALYTICS_ENABLED=true
      - DD_ADONET_ANALYTICS_ENABLED=true
      - DD_ASPNETMVC_ANALYTICS_ENABLED=true
      - DD_WebRequest_ANALYTICS_ENABLED=true
      - DD_SYSTEM_PROBE_ENABLED=true
    depends_on:
      - nosql.data
      - sql.data
      - identity.api
      - rabbitmq
      - ordering.api
      - marketing.api
      - catalog.api
      - basket.api
      - ddagent

  mobilemarketingapigw:
    image: ${REGISTRY:-eshop}/ocelotapigw:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGw-Base/Dockerfile
    environment:
      - DD_TRACE_AGENT_HOSTNAME=ddagent
      - DD_TRACE_AGENT_PORT=8126
      - DD_LOGS_INJECTION=true
      - DD_HttpMessageHandler_ENABLED=false
      - DD_TRACE_ANALYTICS_ENABLED=true
      - DD_ADONET_ANALYTICS_ENABLED=true
      - DD_ASPNETMVC_ANALYTICS_ENABLED=true
      - DD_WebRequest_ANALYTICS_ENABLED=true
      - DD_SYSTEM_PROBE_ENABLED=true
    depends_on:
      - nosql.data
      - sql.data
      - identity.api
      - rabbitmq
      - ordering.api
      - marketing.api
      - catalog.api
      - basket.api
      - ddagent

  webshoppingapigw:
    image: ${REGISTRY:-eshop}/ocelotapigw:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGw-Base/Dockerfile
    environment:
      - DD_TRACE_AGENT_HOSTNAME=ddagent
      - DD_TRACE_AGENT_PORT=8126
      - DD_LOGS_INJECTION=true
      - DD_HttpMessageHandler_ENABLED=false
      - DD_TRACE_ANALYTICS_ENABLED=true
      - DD_ADONET_ANALYTICS_ENABLED=true
      - DD_ASPNETMVC_ANALYTICS_ENABLED=true
      - DD_WebRequest_ANALYTICS_ENABLED=true
      - DD_SYSTEM_PROBE_ENABLED=true
    depends_on:
      - nosql.data
      - sql.data
      - identity.api
      - rabbitmq
      - ordering.api
      - marketing.api
      - catalog.api
      - basket.api
      - ddagent

  webmarketingapigw:
    image: ${REGISTRY:-eshop}/ocelotapigw:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGw-Base/Dockerfile
    environment:
      - DD_TRACE_AGENT_HOSTNAME=ddagent
      - DD_TRACE_AGENT_PORT=8126
      - DD_LOGS_INJECTION=true
      - DD_HttpMessageHandler_ENABLED=false
      - DD_TRACE_ANALYTICS_ENABLED=true
      - DD_ADONET_ANALYTICS_ENABLED=true
      - DD_ASPNETMVC_ANALYTICS_ENABLED=true
      - DD_WebRequest_ANALYTICS_ENABLED=true
      - DD_SYSTEM_PROBE_ENABLED=true
    depends_on:
      - nosql.data
      - sql.data
      - identity.api
      - rabbitmq
      - ordering.api
      - marketing.api
      - catalog.api
      - basket.api
      - ddagent

  mobileshoppingagg:
    image: ${REGISTRY:-eshop}/mobileshoppingagg:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/Mobile.Bff.Shopping/aggregator/Dockerfile
    environment:
      - DD_TRACE_AGENT_HOSTNAME=ddagent
      - DD_TRACE_AGENT_PORT=8126
      - DD_HttpMessageHandler_ENABLED=false
      - DD_TRACE_ANALYTICS_ENABLED=true
      - DD_ADONET_ANALYTICS_ENABLED=true
      - DD_ASPNETMVC_ANALYTICS_ENABLED=true
      - DD_WebRequest_ANALYTICS_ENABLED=true
      - DD_SYSTEM_PROBE_ENABLED=true
    depends_on:
      - nosql.data
      - sql.data
      - identity.api
      - rabbitmq
      - ordering.api
      - marketing.api
      - catalog.api
      - basket.api
      - ddagent

  webshoppingagg:
    image: ${REGISTRY:-eshop}/webshoppingagg:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/Web.Bff.Shopping/aggregator/Dockerfile
    environment:
      - DD_TRACE_AGENT_HOSTNAME=ddagent
      - DD_TRACE_AGENT_PORT=8126
      - DD_LOGS_INJECTION=true
      - DD_HttpMessageHandler_ENABLED=false
      - DD_TRACE_ANALYTICS_ENABLED=true
      - DD_ADONET_ANALYTICS_ENABLED=true
      - DD_ASPNETMVC_ANALYTICS_ENABLED=true
      - DD_WebRequest_ANALYTICS_ENABLED=true
      - DD_SYSTEM_PROBE_ENABLED=true
    depends_on:
      - nosql.data
      - sql.data
      - identity.api
      - rabbitmq
      - ordering.api
      - marketing.api
      - catalog.api
      - basket.api
      - ddagent

  ordering.signalrhub:
    image: ${REGISTRY:-eshop}/ordering.signalrhub:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Ordering/Ordering.SignalrHub/Dockerfile
    environment:
      - DD_TRACE_AGENT_HOSTNAME=ddagent
      - DD_TRACE_AGENT_PORT=8126
      - DD_LOGS_INJECTION=true
      - DD_HttpMessageHandler_ENABLED=false
      - DD_TRACE_ANALYTICS_ENABLED=true
      - DD_ADONET_ANALYTICS_ENABLED=true
      - DD_ASPNETMVC_ANALYTICS_ENABLED=true
      - DD_WebRequest_ANALYTICS_ENABLED=true
      - DD_SYSTEM_PROBE_ENABLED=true
    depends_on:
      - nosql.data
      - sql.data
      - identity.api
      - rabbitmq
      - ordering.api
      - marketing.api
      - catalog.api
      - basket.api
      - ddagent

  webstatus:
    image: ${REGISTRY:-eshop}/webstatus:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Web/WebStatus/Dockerfile

  webspa:
    image: ${REGISTRY:-eshop}/webspa:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Web/WebSPA/Dockerfile    
      args:
        NODE_IMAGE: ${NODE_IMAGE:-node:8.11}
    environment:
      - DD_TRACE_AGENT_HOSTNAME=ddagent
      - DD_TRACE_AGENT_PORT=8126
      - DD_LOGS_INJECTION=true
      - DD_HttpMessageHandler_ENABLED=false
      - DD_TRACE_ANALYTICS_ENABLED=true
      - DD_ADONET_ANALYTICS_ENABLED=true
      - DD_ASPNETMVC_ANALYTICS_ENABLED=true
      - DD_WebRequest_ANALYTICS_ENABLED=true
      - DD_SYSTEM_PROBE_ENABLED=true
    depends_on:
      - ddagent

  webmvc:
    image: ${REGISTRY:-eshop}/webmvc:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Web/WebMVC/Dockerfile
    environment:
      - DD_TRACE_AGENT_HOSTNAME=ddagent
      - DD_TRACE_AGENT_PORT=8126
      - DD_LOGS_INJECTION=true
      - DD_TRACE_ANALYTICS_ENABLED=true
      - DD_ADONET_ANALYTICS_ENABLED=true
      - DD_ASPNETMVC_ANALYTICS_ENABLED=true
      - DD_WebRequest_ANALYTICS_ENABLED=true
      - DD_SYSTEM_PROBE_ENABLED=true
    depends_on:
      - webshoppingagg
      - webshoppingapigw
      - webmarketingapigw
      - ddagent

  webhooks.client:
    image: ${REGISTRY:-eshop}/webhooks.client:${PLATFORM:-linux}-${TAG:-latest}
    network_mode: bridge
    build:
      context: .
      dockerfile: src/Web/WebhookClient/Dockerfile
    environment:
      - DD_TRACE_AGENT_HOSTNAME=ddagent
      - DD_TRACE_AGENT_PORT=8126
      - DD_LOGS_INJECTION=true
      - DD_HttpMessageHandler_ENABLED=false
      - DD_TRACE_ANALYTICS_ENABLED=true
      - DD_ADONET_ANALYTICS_ENABLED=true
      - DD_ASPNETMVC_ANALYTICS_ENABLED=true
      - DD_WebRequest_ANALYTICS_ENABLED=true
      - DD_SYSTEM_PROBE_ENABLED=true
    depends_on:
      - webhooks.api
      - ddagent